ALTER TABLE "CHAT_MESSAGES"
  ADD COLUMN IF NOT EXISTS reply_to INTEGER REFERENCES "CHAT_MESSAGES"(message_id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS answered_verbally BOOLEAN NOT NULL DEFAULT false;
